### PR TITLE
modify image links to github

### PR DESCRIPTION
**Pull request by luanshaotong**

### CODE REVIEW

**Comment by SignorMercurio** [comment]
@luanshaotong The deploy problem is already fixed in `main`, so I'll directly merge this.

**Comment by luanshaotong** [comment]
> @luanshaotong The deploy problem is already fixed in `main`, so I'll directly merge this.

How do I know what's the problem?

**Comment by SignorMercurio** [comment]
@luanshaotong You may try locally:

```shell
yarn build
```

Which should produce the error if vercel deploy failed. Running `yarn start` might not reveal the error.

**Comment by luanshaotong** [comment]
> @luanshaotong You may try locally:
> 
> ```shell
> yarn build
> ```

> Which should produce the error if vercel deploy failed. Running `yarn start` might not reveal the error.

Thanks! I didn't know that before.

**Pull request merged**
